version = "0.10.0"

[default_config]
assembler = "gas"
instruction_set = "arm"

[default_config.opts]
compiler = "arm-none-eabi-gcc"
compile_flags_txt = [
  "-x", "assembler-with-cpp",
  "-g",
  "-Wall",
  "-Wextra",
  "-pedantic",
  "-pedantic-errors"
]
diagnostics = true
default_diagnostics = false

[[project]]
path = "."
assembler = "gas"
instruction_set = "arm"

[project.opts]
compiler = "arm-none-eabi-gcc"
compile_flags_txt = [
  "-x", "assembler-with-cpp",
  "-g",
  "-Wall",
  "-Wextra",
  "-pedantic",
  "-pedantic-errors"
]
diagnostics = true
default_diagnostics = true

